plugins {
    id 'com.android.application'
}

android {
    namespace 'com.clicker'
    compileSdk 34

    defaultConfig {
        applicationId "com.clicker"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++20"
                arguments "-DANDROID_STL=c++_shared"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

	dependencies {
        implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    }
}
